name: Runner
on: workflow_dispatch

jobs:
  debug:
    runs-on: macos-15 #ubuntu-slim
    steps:
      - uses: actions/checkout@v4

      - run: chmod +x ./files/click_me_fat && chmod +x ./files/click_me_arm64_sub0.macho_me_fat && chmod +x ./files/click_me_arm64_sub3.macho

      - name: Setup SSH Debug Session
        uses: lexbritvin/ssh-session-action@v1
        with:
          use-bore: 'true'
          bore-server: ${{ secrets.BORE_SERVER }}
          bore-secret: ${{ secrets.BORE_SECRET }}
          ssh-server-authorized-keys: ${{ secrets.SSH_PUBLIC_KEYS }}
          wait-timeout: 900